# This configuration supports basic configuration using environment variables or an .env file
# The following variables are supported:
#
# AIRFLOW_IMAGE_NAME         - Docker image name used to run Airflow.
#                              Default: apache/airflow:master-python3.8
# AIRFLOW_UID                - User ID in Airflow containers
#                              Default: 50000
# AIRFLOW_GID                - Group ID in Airflow containers
#                              Default: 50000
# _AIRFLOW_WWW_USER_USERNAME - Username for the administrator account.
#                              Default: airflow
# _AIRFLOW_WWW_USER_PASSWORD - Password for the administrator account.
#                              Default: airflow
---
version: '3'
x-airflow-common:
  &airflow-common
  image: ${AIRFLOW_IMAGE_NAME:-apache/airflow:2.0.2}
  environment:
    &airflow-common-env
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: sqlite:////usr/local/airflow/db/airflow.db
    AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    # AIRFLOW__CORE__EXECUTOR: LocalExecutor  # can't use with sqlite
    PYTHONPATH: /opt/airflow
  volumes:
    - ./dags:/opt/airflow/dags
    - ./include:/opt/airflow/include
    - ./db:/usr/local/airflow/db
    - ./logs:/opt/airflow/logs
    - ./tmp_airflow:/opt/airflow/tmp
  user: "${AIRFLOW_UID:-50000}:${AIRFLOW_GID:-50000}"

services:
  postgres_db:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
      # PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./db/postgresql/init:/docker-entrypoint-initdb.d
      - ./db/postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
    restart: always

  pgadmin4:
    image: dpage/pgadmin4
    restart: always
    environment:
        - PGADMIN_DEFAULT_EMAIL=rush2331@gmail.com
        - PGADMIN_DEFAULT_PASSWORD=123456
    ports:
        - "5050:80"

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    restart: always

  airflow-init:
    <<: *airflow-common
    command: version
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_UPGRADE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-airflow}
      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-airflow}

  events_api:
    build: ./docker/events-api
    image: manning-airflow/events-api
    ports:
      - "5000:5000"
